# Generated by Django 5.2.5 on 2026-02-26 11:19

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Автоматически устанавливается при создании записи', verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Автоматически обновляется при каждом сохранении записи', verbose_name='Дата изменения')),
                ('is_deleted', models.BooleanField(default=False, help_text='Пометка для мягкого удаления записи (без фактического удаления из БД)', verbose_name='Удалено')),
                ('name', models.CharField(help_text='Например: "Haas VF-2", "DMG MORI CMX 1100 Vc"', max_length=200, unique=True, verbose_name='Название модели')),
                ('manufacturer', models.CharField(blank=True, max_length=100, verbose_name='Производитель')),
                ('description', models.TextField(blank=True, help_text='Технические характеристики и особенности модели', verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Модель станка',
                'verbose_name_plural': 'Модели станков',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StageType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Автоматически устанавливается при создании записи', verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Автоматически обновляется при каждом сохранении записи', verbose_name='Дата изменения')),
                ('is_deleted', models.BooleanField(default=False, help_text='Пометка для мягкого удаления записи (без фактического удаления из БД)', verbose_name='Удалено')),
                ('name', models.CharField(help_text='Например: "Фрезеровка", "Токарная обработка", "Термообработка"', max_length=200, unique=True, verbose_name='Название этапа')),
                ('description', models.TextField(blank=True, help_text='Подробное описание данного этапа', verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Тип этапа',
                'verbose_name_plural': 'Типы этапов',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Автоматически устанавливается при создании записи', verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Автоматически обновляется при каждом сохранении записи', verbose_name='Дата изменения')),
                ('is_deleted', models.BooleanField(default=False, help_text='Пометка для мягкого удаления записи (без фактического удаления из БД)', verbose_name='Удалено')),
                ('name', models.CharField(help_text='Например: "В работе", "Завершено", "Ожидание", "Неисправен"', max_length=100, unique=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, help_text='Дополнительная информация о статусе', verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Статусы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Автоматически устанавливается при создании записи', verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Автоматически обновляется при каждом сохранении записи', verbose_name='Дата изменения')),
                ('is_deleted', models.BooleanField(default=False, help_text='Пометка для мягкого удаления записи (без фактического удаления из БД)', verbose_name='Удалено')),
                ('name', models.CharField(help_text='Например: "Механический цех №1", "Сборочный цех"', max_length=200, unique=True, verbose_name='Название цеха')),
                ('code', models.CharField(blank=True, help_text='Краткое обозначение, например: "МЦ-01"', max_length=20, unique=True, verbose_name='Код цеха')),
                ('description', models.TextField(blank=True, help_text='Расположение, начальник цеха, особенности', verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Цех',
                'verbose_name_plural': 'Цеха',
                'ordering': ['code', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Автоматически устанавливается при создании записи', verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Автоматически обновляется при каждом сохранении записи', verbose_name='Дата изменения')),
                ('is_deleted', models.BooleanField(default=False, help_text='Пометка для мягкого удаления записи (без фактического удаления из БД)', verbose_name='Удалено')),
                ('inventory_number', models.CharField(help_text='Уникальный инвентарный номер станка на предприятии', max_length=50, unique=True, verbose_name='Инвентарный номер')),
                ('load_percent', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Загрузка (%)')),
                ('commissioning_date', models.DateField(blank=True, null=True, verbose_name='Дата ввода в эксплуатацию')),
                ('last_maintenance_date', models.DateField(blank=True, help_text='Дата последнего технического обслуживания', null=True, verbose_name='Дата последнего ТО')),
                ('model', models.ForeignKey(help_text='Ссылка на модель станка из справочника', on_delete=django.db.models.deletion.PROTECT, related_name='machines', to='core.machinemodel', verbose_name='Модель')),
                ('status', models.ForeignKey(help_text='Текущее состояние станка (работает, ремонт, ожидание и т.д.)', on_delete=django.db.models.deletion.PROTECT, related_name='machines', to='core.status', verbose_name='Статус')),
                ('workshop', models.ForeignKey(help_text='Цех, в котором установлен станок', on_delete=django.db.models.deletion.PROTECT, related_name='machines', to='core.workshop', verbose_name='Цех')),
            ],
            options={
                'verbose_name': 'Станок',
                'verbose_name_plural': 'Станки',
                'ordering': ['model', 'inventory_number'],
            },
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Автоматически устанавливается при создании записи', verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Автоматически обновляется при каждом сохранении записи', verbose_name='Дата изменения')),
                ('is_deleted', models.BooleanField(default=False, help_text='Пометка для мягкого удаления записи (без фактического удаления из БД)', verbose_name='Удалено')),
                ('article', models.CharField(help_text='Артикул детали в системе учёта', max_length=100, verbose_name='Артикул')),
                ('name', models.CharField(help_text='Полное наименование детали', max_length=255, verbose_name='Название')),
                ('drawing_number', models.CharField(help_text='Номер чертежа или КД', max_length=100, verbose_name='Номер чертежа')),
                ('planned_completion_date', models.DateTimeField(blank=True, null=True, verbose_name='Плановая дата готовности')),
                ('completion_percent', models.DecimalField(decimal_places=2, default=0, help_text='Рассчитывается автоматически на основе выполненных этапов', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Готовность (%)')),
                ('description', models.TextField(blank=True, help_text='Дополнительная информация о детали', verbose_name='Описание')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='details', to='core.status', verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Деталь',
                'verbose_name_plural': 'Детали',
                'ordering': ['article'],
            },
        ),
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Автоматически устанавливается при создании записи', verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Автоматически обновляется при каждом сохранении записи', verbose_name='Дата изменения')),
                ('is_deleted', models.BooleanField(default=False, help_text='Пометка для мягкого удаления записи (без фактического удаления из БД)', verbose_name='Удалено')),
                ('action_type', models.CharField(choices=[('CREATE', 'Создание'), ('UPDATE', 'Изменение'), ('DELETE', 'Удаление'), ('STATUS_CHANGE', 'Смена статуса'), ('STAGE_COMPLETE', 'Этап выполнен'), ('RECALCULATE', 'Пересчет готовности'), ('ASSIGNMENT', 'Назначение на станок')], max_length=50, verbose_name='Тип действия')),
                ('entity_type', models.CharField(max_length=50, verbose_name='Тип объекта')),
                ('entity_id', models.PositiveIntegerField(verbose_name='ID объекта')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('changes_json', models.JSONField(blank=True, null=True, verbose_name='Изменения')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_logs', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Запись журнала',
                'verbose_name_plural': 'Журнал действий',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='core_logent_user_id_0c32bd_idx'), models.Index(fields=['action_type'], name='core_logent_action__531a0e_idx'), models.Index(fields=['entity_type', 'entity_id'], name='core_logent_entity__18075a_idx')],
            },
        ),
        migrations.CreateModel(
            name='MachineAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Автоматически устанавливается при создании записи', verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Автоматически обновляется при каждом сохранении записи', verbose_name='Дата изменения')),
                ('is_deleted', models.BooleanField(default=False, help_text='Пометка для мягкого удаления записи (без фактического удаления из БД)', verbose_name='Удалено')),
                ('assignment_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата назначения')),
                ('planned_start', models.DateTimeField(help_text='Планируемая дата и время начала обработки', verbose_name='Плановое начало')),
                ('actual_start', models.DateTimeField(blank=True, help_text='Фактическая дата и время начала обработки', null=True, verbose_name='Фактическое начало')),
                ('planned_end', models.DateTimeField(help_text='Планируемая дата и время завершения обработки', verbose_name='Плановое завершение')),
                ('actual_end', models.DateTimeField(blank=True, help_text='Фактическая дата и время завершения обработки', null=True, verbose_name='Фактическое завершение')),
                ('notes', models.TextField(blank=True, help_text='Дополнительная информация о назначении', verbose_name='Примечания')),
                ('detail', models.ForeignKey(help_text='Деталь, которая будет обрабатываться', on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='core.detail', verbose_name='Деталь')),
                ('machine', models.ForeignKey(help_text='Станок, на который назначается деталь', on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='core.machine', verbose_name='Станок')),
            ],
            options={
                'verbose_name': 'Назначение на станок',
                'verbose_name_plural': 'Назначения на станки',
                'ordering': ['-planned_start'],
                'indexes': [models.Index(fields=['machine'], name='core_machin_machine_da9ed4_idx'), models.Index(fields=['detail'], name='core_machin_detail__5cc04d_idx'), models.Index(fields=['actual_start', 'actual_end'], name='core_machin_actual__db70da_idx')],
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Автоматически устанавливается при создании записи', verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Автоматически обновляется при каждом сохранении записи', verbose_name='Дата изменения')),
                ('is_deleted', models.BooleanField(default=False, help_text='Пометка для мягкого удаления записи (без фактического удаления из БД)', verbose_name='Удалено')),
                ('order_num', models.PositiveIntegerField(help_text='Порядок выполнения этапа в технологическом маршруте', verbose_name='Порядковый номер')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Выполнен')),
                ('completion_date', models.DateTimeField(blank=True, help_text='Отметка о выполнении этапа', null=True, verbose_name='Дата выполнения')),
                ('notes', models.TextField(blank=True, help_text='Особые отметки по выполнению этапа', verbose_name='Примечания')),
                ('detail', models.ForeignKey(help_text='Деталь, для которой определён этот этап', on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='core.detail', verbose_name='Деталь')),
                ('machine', models.ForeignKey(help_text='Станок, на котором выполняется этот этап', on_delete=django.db.models.deletion.PROTECT, related_name='stages', to='core.machine', verbose_name='Станок')),
                ('stage_type', models.ForeignKey(help_text='Ссылка на название этапа из справочника', on_delete=django.db.models.deletion.PROTECT, related_name='stages', to='core.stagetype', verbose_name='Название этапа')),
            ],
            options={
                'verbose_name': 'Этап обработки',
                'verbose_name_plural': 'Этапы обработки',
                'ordering': ['detail', 'order_num'],
                'indexes': [models.Index(fields=['detail'], name='core_stage_detail__437bd0_idx'), models.Index(fields=['machine'], name='core_stage_machine_09d137_idx')],
                'unique_together': {('detail', 'order_num')},
            },
        ),
        migrations.AddIndex(
            model_name='detail',
            index=models.Index(fields=['article'], name='core_detail_article_d70ec8_idx'),
        ),
        migrations.AddIndex(
            model_name='detail',
            index=models.Index(fields=['drawing_number'], name='core_detail_drawing_f5f622_idx'),
        ),
        migrations.AddIndex(
            model_name='detail',
            index=models.Index(fields=['status'], name='core_detail_status__b772ff_idx'),
        ),
        migrations.AddIndex(
            model_name='detail',
            index=models.Index(fields=['planned_completion_date'], name='core_detail_planned_b4ca5b_idx'),
        ),
        migrations.AddIndex(
            model_name='machine',
            index=models.Index(fields=['inventory_number'], name='core_machin_invento_cb5a74_idx'),
        ),
        migrations.AddIndex(
            model_name='machine',
            index=models.Index(fields=['model'], name='core_machin_model_i_6f7f50_idx'),
        ),
        migrations.AddIndex(
            model_name='machine',
            index=models.Index(fields=['status'], name='core_machin_status__10ef06_idx'),
        ),
        migrations.AddIndex(
            model_name='machine',
            index=models.Index(fields=['workshop'], name='core_machin_worksho_a00bb3_idx'),
        ),
    ]
